### PR TITLE
chore(front-matter): release `front-matter@1.0.0`

### LINKED ISSUE #5016: stabilize `@std/front-matter`
part of #4600 

- [x] fully documented
- [ ] fully tested
- [x] no ongoing breaking change discussion
- [ ] 1.0.0-rc.1
- [ ] wait 1 month
- [ ] 1.0.0 (stabilization)

### PR DESCRIPTION
**Pull request by kt3k**
towards #4600

The latest API docs: https://jsr.io/@std/front-matter@1.0.0-rc.1/doc

To be merged July 24.

closes #5016

### CODE REVIEW

**Comment by littledivy** [comment]
image

https://jsr.io/@std/front-matter@1.0.0-rc.1/doc

The description is a bit confusing  because `Extractor` seems to be an internal type.

**Comment by kt3k** [comment]
@littledivy Good point! Thanks. Fixing in https://github.com/denoland/deno_std/pull/5383

**Review by littledivy — APPROVED** [review]
LGTM!

**Review by iuioiua — APPROVED** [review]
LGTM!

**Pull request merged**
