### PR TITLE
chore(yaml): release `yaml@1.0.0`

### LINKED ISSUE #5015: stabilize `@std/yaml`
part of #4600 

- [x] fully documented
- [ ] fully tested
- [x] no ongoing breaking change discussion
- [ ] 1.0.0-rc.1
- [ ] wait 1 month
- [ ] 1.0.0 (stabilization)

### PR DESCRIPTION
**Pull request by iuioiua**
Docs: https://jsr.io/@std/yaml@1.0.0-rc.4

To be merged July 23.

Closes #5015

### CODE REVIEW

**Review by satyarohith — COMMENTED** [review]
Looks good in general. I think these two can be achievable before release to get 100% score?
CleanShot 2024-07-22 at 11 20 16@2x

**Comment by kt3k** [comment]
@satyarohith I think these issue are addressed in the latest RC version (`1.0.0-rc.4`) (I guess the score is calculated based on the last non-prerelease version (`0.224.3`)

**Review by satyarohith — APPROVED** [review]
@kt3k thanks Yoshiya! I opened an issue in [JSR](https://github.com/jsr-io/jsr/issues/663) to support score for pre-release versions.

LGTM in case the issues are already addressed.

**Comment by iuioiua** [comment]
I'm not yet confident testing is sufficient, namely that options all do what they should and that [`Type`](https://app.codecov.io/gh/denoland/std/tree/main/yaml%2F_type)s are sufficently tested. Let's work a little more on this. I should have time to focus on this tomorrow.

**Comment by iuioiua** [comment]
Testing LGTM now

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
