### PR TITLE
docs(path): add examples to `@std/path/posix` examples

### PR DESCRIPTION
**Pull request by iuioiua**
This documentation aims at providing sufficient guidance to justify removing `@std/url`.

Pre-requisite for #5530
Addresses https://github.com/denoland/std/pull/4992#pullrequestreview-2166480173

### CODE REVIEW

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by kt3k** [comment]
I think we should also explore the idea (from @lucacasonato ) of making some of `path` APIs directly accept file URL object and file URL strings like some of FS APIs in Deno CLI:

```ts
dirname("file:///path/to/dir/file"); //=> returns `/path/to/dir` on linux
dirname("file:///C:/path/to/dir/file"); // => returns `C:\path\to\dir` on windows
```

I think this mostly covers the motivation of `std/url`

**Comment by iuioiua** [comment]
Let's explore in a separate issue 🙂

**Comment by kt3k** [comment]
created #5537

**Pull request merged**
