### PR TITLE
chore(fs): release `fs@1.0.0`

### LINKED ISSUE #5008: stabilize `@std/fs`
part of #4600 

- [ ] fully documented
- [ ] fully tested
- [x] no ongoing breaking change discussion
- [ ] 1.0.0-rc.1
- [ ] wait 1 month
- [ ] 1.0.0 (stabilization)

### PR DESCRIPTION
**Pull request by iuioiua**
To be merged July 20.

Closes #5008

### CODE REVIEW

**Review by satyarohith — COMMENTED** [review]
Conflicts need to be resolved otherwise the docs looks good 👍 

The JSR score is 94% because this specific item is not actionable for fs module
CleanShot 2024-07-16 at 20 49 06@2x

**Review by satyarohith — APPROVED** [review]

**Comment by iuioiua** [comment]
PTAL, @kt3k

**Comment by iuioiua** [comment]
LGTM once #5532 is merged. Though, for after stabilization, we can still improve documentation. Specifically, how different options for different APIs can be used.

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
