### PR TITLE
chore: clarify the policy about new features

### PR DESCRIPTION
**Pull request by kt3k**

### CODE REVIEW

**Review by iuioiua — APPROVED** [review]
I think it's good that this **doesn't** include timelines. LGTM.

**Comment by iuioiua** [comment]
I think we can make exceptions for APIs that we are highly confident will not yield unexpected behavior. E.g. #5573 is fine to add as stable.

**Review by ry — COMMENTED** [review]
Do we have a mechanism to mark APIs as unstable? Is there a special jsdoc markup?

**Comment by kt3k** [comment]
> Do we have a mechanism to mark APIs as unstable? Is there a special jsdoc markup?

Yes for symbols https://jsr.io/@std/cli/doc/~/Spinner

But I'm not sure about the way to mark specific parameter in function as unstable. (which is necessary for the case like #5573 )

**Comment by crowlKats** [comment]
@kt3k sadly both jsdoc and tsdoc dont have a way to mark unstable/experimental parameters. the only way i can think of is having overloads, where the overload with an unstable parameter is marked as unstable

**Comment by kt3k** [comment]
@crowlKats Ah, ok. Thanks for the input! Then we probably need to do overloads when an API is partially unstable.

**Pull request merged**
