### PR TITLE
test(yaml): add regexp type tests

### PR DESCRIPTION
**Pull request by timreichen**

### CODE REVIEW

**Comment by iuioiua** [comment]
This doesn't seem to increase test coverage for the code changed in #5860

**Comment by timreichen** [comment]
> This doesn't seem to increase test coverage for the code changed in #5860

Sorry, I uploaded the wrong branch. Should be fixed now.

**Review by iuioiua — COMMENTED** [review]
Any chance you'd be able to cover [this line](https://app.codecov.io/gh/denoland/std/pull/5862/indirect-changes#32d1a0fb9401849a82221cad231234f7-R25)?

**Review by iuioiua — APPROVED** [review]
Actually, I'll merge as-is. Thank you!

**Pull request merged**
