### PR TITLE
fix(front-matter): extend generic `Extract` type

### PR DESCRIPTION
**Pull request by timreichen**
**Changes**
This PR makes `Extract` generic extend `Record<string, unknown>` as `Parser` returns the same type.

### CODE REVIEW

**Comment by kt3k** [comment]
I think `T` can be `string`, `number`, `string[]`, etc.

In the below example T is `string[]`

```ts
import { extract } from "@std/front-matter/yaml";

const x = extract<string[]>(`---
- foo
- bar
- baz
---
body
`);

console.log(x);
```

**Comment by timreichen** [comment]
> I think `T` can be `string`, `number`, `string[]`, etc.
> 
> 
> 
> In the below example T is `string[]`
> 
> 
> 
> ```ts
> 
> import { extract } from "@std/front-matter/yaml";
> 
> 
> 
> const x = extract<string[]>(`---
> 
> - foo
> 
> - bar
> 
> - baz
> 
> ---
> 
> body
> 
> `);
> 
> 
> 
> console.log(x);
> 
> ```

In that case `Parser` probably has a wrong return type. I'll investigate and update this PR.

**Comment by kt3k** [comment]
I don't see the reason to introduce type parameters to `toml.parse` and `yaml.parse`. These changes seem undesirable and also unnecessary to me

**Comment by kt3k** [comment]
> This PR makes Extract generic extend Record<string, unknown> as Parser returns the same type.

What's the purpose of limiting that type? I don't see the reason well.

**Comment by kt3k** [comment]
The result of `parse` can vary depending on the config language. I think it is difficult to type these correctly, and also I don't see much value in this.

**Comment by iuioiua** [comment]
I tend to agree with Yoshiya. I think these changes aren't needed.

**Comment by iuioiua** [comment]
Closing this for the reasons above. Either way, thank you for the contribution.

**Pull request closed without merging**
