### PR TITLE
BREAKING(archive): remove std/archive package

### LINKED ISSUE #5986: to-do: deprecate and remove `@std/archive`
We now have the streams-based `@std/tar`. In order to deprecate and remove the old `@std/archive`, we must first migrate:

- [x] [jsr:@deno/wasmbuild](https://jsr.io/@deno/wasmbuild)
- [x] [jsr:@libs/bundle](https://jsr.io/@libs/bundle)
- [x] [jsr:@libs/std](https://jsr.io/@libs/std)
- [x] [jsr:@polyseam/inflate-response](https://jsr.io/@polyseam/inflate-response)

### PR DESCRIPTION
**Pull request by kt3k**
`@std/archive` was deprecated in https://github.com/denoland/std/pull/5988 in favor `@std/tar`.

This PR now removes the `@std/archive` from the codebase.

close #5986

### CODE REVIEW

**Comment by iuioiua** [comment]
Nice to see this done. The packages table in `README.md` and dependency graph (`deno task lint:circular --graph`) also need to be adjusted.

**Comment by kt3k** [comment]
That's correct. Thanks! Updated

**Review by satyarohith — APPROVED** [review]
LGTM.

I don't seen any instances of archive module been used:
```
➜  deno_std git:(remove-archive) git grep archive
Releases.md:#### @std/archive 0.225.4 (patch)
Releases.md:- deprecation(archive/unstable): deprecate `@std/archive` (#5988)
Releases.md:- docs(archive): clarify deprecation notices (#6034)
Releases.md:- docs(archive): update `@std/archive` deprecation notices (#6028)
Releases.md:- docs(archive,log,testing): correct typos (#5995)
Releases.md:- docs(archive,log,testing): correct typos (#5995)
Releases.md:- docs(archive,log,testing): correct typos (#5995)
Releases.md:#### @std/archive 0.225.3 (patch)
Releases.md:- refactor(archive,io): use `Seeker[Sync]` from `@std/io/types` (#5943)
Releases.md:- refactor(archive,io): use `Seeker[Sync]` from `@std/io/types` (#5943)
Releases.md:#### @std/archive 0.225.2 (patch)
Releases.md:- feat(archive): `UntarStream` and `TarStream` (#4548)
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:- refactor(archive,async,cli,csv,dotenv,encoding,expect,fmt,front-matter,fs,http,internal,log,net,path,semver,testing,text,webgpu,yaml):
Releases.md:#### @std/archive 0.225.1 (patch)
Releases.md:- docs(archive,assert,cache,cli,encoding,html,http,net,streams,text): remove
Releases.md:- docs(archive): complete documentation (#5636)
Releases.md:- refactor(archive,cache,datetime,fmt,front-matter): align error messages to the
Releases.md:- docs(archive,assert,cache,cli,encoding,html,http,net,streams,text): remove
Releases.md:- docs(archive,assert,cache,cli,encoding,html,http,net,streams,text): remove
Releases.md:- refactor(archive,cache,datetime,fmt,front-matter): align error messages to the
Releases.md:- docs(archive,assert,cache,cli,encoding,html,http,net,streams,text): remove
Releases.md:- refactor(archive,cache,datetime,fmt,front-matter): align error messages to the
Releases.md:- docs(archive,assert,cache,cli,encoding,html,http,net,streams,text): remove
Releases.md:- refactor(archive,cache,datetime,fmt,front-matter): align error messages to the
Releases.md:- refactor(archive,cache,datetime,fmt,front-matter): align error messages to the
Releases.md:- docs(archive,assert,cache,cli,encoding,html,http,net,streams,text): remove
Releases.md:- docs(archive,assert,cache,cli,encoding,html,http,net,streams,text): remove
Releases.md:- docs(archive,assert,cache,cli,encoding,html,http,net,streams,text): remove
Releases.md:- docs(archive,assert,cache,cli,encoding,html,http,net,streams,text): remove
Releases.md:- docs(archive,assert,cache,cli,encoding,html,http,net,streams,text): remove
Releases.md:#### @std/archive 0.225.0 (minor)
Releases.md:- BREAKING(archive): remove `TarEntry.#header` (#5638)
Releases.md:- fix(archive): make `data` property private in `Tar` (#5645)
Releases.md:- fix(archive): make `block` and `reader` properties in `Untar` private (#5637)
Releases.md:- docs(archive): mark public APIs as unstable/experimental (#5639)
Releases.md:#### @std/archive 0.224.3 (patch)
Releases.md:- test(archive): fix typo in `tar_test.ts` (#5196)
Releases.md:#### @std/archive 0.224.2 (patch)
Releases.md:- refactor(archive,expect,io,log,toml,yaml): remove `private` and `public`
Releases.md:- refactor(archive,expect,io,log,toml,yaml): remove `private` and `public`
Releases.md:- refactor(archive,expect,io,log,toml,yaml): remove `private` and `public`
Releases.md:- refactor(archive,expect,io,log,toml,yaml): remove `private` and `public`
Releases.md:- refactor(archive,expect,io,log,toml,yaml): remove `private` and `public`
Releases.md:- refactor(archive,expect,io,log,toml,yaml): remove `private` and `public`
Releases.md:#### @std/archive 0.224.1 (patch)
Releases.md:- refactor(archive): cleanup use of `@std/assert` (#4975)
Releases.md:- fix(archive/untar.ts): cannot access symlinks in archives (#3686)
Releases.md:- BREAKING(streams, archive): remove deprecated exports (#3107)
Releases.md:- BREAKING(archive): move to single-export files (#2958)
Releases.md:- fix(archive/tar): export TarEntry class (#2429)
media_types/vendor/db.ts:  "application/java-archive": {
media_types/vendor/db.ts:  "application/vnd.android.package-archive": {
media_types/vendor/db.ts:  "application/vnd.joost.joda-archive": {
media_types/vendor/db.ts:  "application/vnd.maxar.archive.3tz+zip": {
media_types/vendor/db.ts:  "application/vnd.smintio.portals.archive": {
media_types/vendor/db.ts:  "application/vnd.tao.intent-module-archive": {
media_types/vendor/db.ts:  "application/x-java-archive-diff": {
tar/mod.ts: * Streaming utilities for working with tar archives.
tar/mod.ts: * Files are not compressed, only collected into the archive.
tar/tar_stream.ts:   * The path to the file, relative to the archive's root directory.
tar/tar_stream.ts:   * The path of the directory, relative to the archive's root directory.
tar/tar_stream.ts: * A TransformStream to create a tar archive. Tar archives allow for storing
tar/tar_stream.ts: * multiple files in a single file (called an archive, or sometimes a tarball).
tar/tar_stream.ts: *   These archives typically have a single '.tar' extension.  This
tar/tar_stream.ts: * The ustar file format is used for creating the tar archive.  While this
tar/tar_stream.ts: * Tar archives are not compressed by default.  If you'd like to compress the
tar/tar_stream.ts: * archive, you may do so by piping it through a compression stream.
tar/tar_stream.ts:              "Cannot add to the tar archive: The size cannot exceed 64 Gibs",
tar/tar_stream.ts:              `Cannot add to the tar archive: The provided size (${chunk.size}) did not match bytes read from provided readable (${size})`,
tar/tar_stream.ts: *   .pipeTo((await Deno.create('./out/archive.tar.gz')).writable);
tar/tar_stream.ts: *   .pipeTo((await Deno.create('./out/archive.tar.gz')).writable);
tar/tar_stream.ts:  ) throw new TypeError("Cannot add to the tar archive: Invalid Mode provided");
tar/tar_stream.ts:  ) throw new TypeError("Cannot add to the tar archive: Invalid UID provided");
tar/tar_stream.ts:  ) throw new TypeError("Cannot add to the tar archive: Invalid GID provided");
tar/tar_stream.ts:      "Cannot add to the tar archive: Invalid MTime provided",
tar/tar_stream.ts:      "Cannot add to the tar archive: Invalid UName provided",
tar/tar_stream.ts:      "Cannot add to the tar archive: Invalid GName provided",
tar/tar_stream.ts:      "Cannot add to the tar archive: Invalid DevMajor provided",
tar/tar_stream.ts:      "Cannot add to the tar archive: Invalid DevMinor provided",
tar/tar_stream_test.ts:    "Cannot add to the tar archive: The size cannot exceed 64 Gibs",
tar/tar_stream_test.ts:    "Cannot add to the tar archive: The size cannot exceed 64 Gibs",
tar/tar_stream_test.ts:    "Cannot add to the tar archive: The size cannot exceed 64 Gibs",
tar/tar_stream_test.ts:    "Cannot add to the tar archive: The provided size (13) did not match bytes read from provided readable (12)",
tar/untar_stream.ts: * The original tar	archive	header format.
tar/untar_stream.ts: * The POSIX ustar archive header format.
tar/untar_stream.ts: * The structure of an entry extracted from a Tar archive.
tar/untar_stream.ts:   * The path of the entry as stated in the archive.
tar/untar_stream.ts: * A TransformStream to expand a tar archive.  Tar archives allow for storing
tar/untar_stream.ts: * multiple files in a single file (called an archive, or sometimes a tarball).
tar/untar_stream.ts: * These archives typically have a single '.tar' extension.  This
tar/untar_stream.ts: * When expanding the archive, as demonstrated in the example, one must decide
tar/untar_stream.ts: * A tar archive may be compressed, often identified by an additional file
tar/untar_stream.ts: * decompression which must be done before expanding the archive.
tar/untar_stream.ts:        `Cannot extract the tar archive: The tarball chunk has an unexpected number of bytes (${value.length})`,
tar/untar_stream.ts:          "Cannot extract the tar archive: The tarball is too small to be valid",
tar/untar_stream.ts:          "Cannot extract the tar archive: The tarball has invalid ending",
tar/untar_stream.ts:          "Cannot extract the tar archive: An archive entry has invalid header checksum",
tar/untar_stream.ts:          "Cannot extract the tar archive: Unexpected end of Tarball",
tar/untar_stream_test.ts:    "Cannot extract the tar archive: The tarball chunk has an unexpected number of bytes (412)",
tar/untar_stream_test.ts:    "Cannot extract the tar archive: The tarball has invalid ending",
tar/untar_stream_test.ts:    "Cannot extract the tar archive: The tarball is too small to be valid",
tar/untar_stream_test.ts:    "Cannot extract the tar archive: An archive entry has invalid header checksum",

```

**Comment by kt3k** [comment]
Discussed this in more details internally, and we are in agreement with this move.

**Comment by iuioiua** [comment]
I believe [`@std/archive`](https://jsr.io/@std/archive) can be archived in JSR now.

**Comment by kt3k** [comment]
Yes. Archived 👍

**Comment by typed-sigterm** [comment]
So archive is archived :)

**Pull request merged**
