### PR TITLE
feat(text/unstable): add `toConstantCase()`

### PR DESCRIPTION
**Pull request by guy-borderless**
per discussion at https://github.com/denoland/deno_std/issues/3125#issuecomment-2180354086

### CODE REVIEW

**Review by iuioiua — APPROVED** [review]
Nice! Thank you. I prefer this name more. Let's see what others think.

**Comment by kt3k** [comment]
Looks good to me. `@std/text` is now in the process of stabilization #4999. Let's land after 1.0.0 of `@std/text` published.

**Comment by guy-borderless** [comment]
The current implementation of splitToWords() only supports Latin letters. This commit adds a unicode-compatible implementation + support for WordSpliting according to case. I can open it in a separate PR if you prefer.

**Comment by iuioiua** [comment]
> The current implementation of splitToWords() only supports Latin letters. This commit adds a unicode-compatible implementation + support for WordSpliting according to case. I can open it in a separate PR if you prefer.

Nice! Thank you. Yes, could you please open a separate PR?

**Comment by guy-borderless** [comment]
> Nice! Thank you. Yes, could you please open a separate PR?

[moved](https://github.com/denoland/std/pull/5447)

**Review by iuioiua — CHANGES_REQUESTED** [review]
Since this PR was created, we split up the word utility files in #5428. Can you please rebase?

**Review by iuioiua — APPROVED** [review]

**Pull request merged**
