### PR TITLE
BREAKING(datetime): replace `utc` with `timeZone` option

### PR DESCRIPTION
**Pull request by timreichen**
**Changes**
This PR changes the `utc` boolean option to `timeZone` with explicit `"UTC"` value option.

**Reasoning**
This makes the option extendable if needed and aligns the api to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString#using_options

### CODE REVIEW

**Review by iuioiua — APPROVED** [review]
Seems fine to me.

**Comment by kt3k** [comment]
Our formatter seems only supporting utc and local timezones? (because we use `Date` under the hood). ref. https://github.com/denoland/std/blob/96d70203cd85c9598477755e196f5431fba380c8/datetime/_date_time_formatter.ts#L154

Doesn't this give the false sense of other timezones being supported?

**Comment by timreichen** [comment]
> Our formatter seems only supporting utc and local timezones? (because we use `Date` under the hood). ref.
> 
> https://github.com/denoland/std/blob/96d70203cd85c9598477755e196f5431fba380c8/datetime/_date_time_formatter.ts#L154
> 
> Doesn't this give the false sense of other timezones being supported?

I think it is clear that only `UTC` is supported, because it is the only valid value. If you want we can add a check and throw an error for invalid timezone values (other than `UTC` here, or maybe even better case insensitive) like in [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat).

**Comment by iuioiua** [comment]
My take: it doesn't matter too much, either way.

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
