### PR TITLE
chore(ini): release `ini@1.0.0`

### LINKED ISSUE #5017: stabilize `@std/ini`
part of #4600 

- [x] fully documented
- [ ] fully tested
- [x] no ongoing breaking change discussion
- [ ] 1.0.0-rc.1
- [ ] wait 1 month
- [ ] 1.0.0 (stabilization)

### PR DESCRIPTION
**Pull request by iuioiua**
To be merged July 31.

Documentation: https://jsr.io/@std/ini@1.0.0-rc.2

Closes #5017

### CODE REVIEW

**Review by kt3k — APPROVED** [review]
LGTM

@dsherret We dropped `IniMap` from public API. We also cleaned up some stringify options in #5572 PTAL https://jsr.io/@std/ini@1.0.0-rc.2

**Comment by dsherret** [comment]
I think maybe we should resolve this one before stabilizing: https://github.com/denoland/std/issues/4807

**Comment by dsherret** [comment]
The ini module looks good to me!

Just note that there are a few outstanding bugs:

* https://github.com/denoland/std/issues/4809
* https://github.com/denoland/std/issues/4808

**Review by dsherret — APPROVED** [review]

**Comment by kt3k** [comment]
We are not stabilizing `ini` soon. Closing this PR for now

ref https://github.com/denoland/std/issues/5615

**Pull request closed without merging**
