### PR TITLE
feat(collections/unstable): support `Iterable` argument in `takeWhile()`

### PR DESCRIPTION
**Pull request by Liam-Tait**
Support `Iterable` for collections `takeWhile`

#5470

### CODE REVIEW

**Review by iuioiua — APPROVED** [review]
Nice! LGTM. @kt3k, how do you prefer we handle this, in terms of stability?

**Comment by kt3k** [comment]
> how do you prefer we handle this, in terms of stability?

I'd prefer to avoid overloading with this.

How about considering this as 'refactor' or 'fix'?

**Comment by kt3k** [comment]
Maybe we can just land this as `feat(collections/unstable)` without overloading, but with note of something like `Iterable input is unstable`. WDYT?

**Comment by iuioiua** [comment]
> Or, maybe we can just land this as `feat(collections/unstable)` without overloading, but with note of something like `Iterable input is unstable`. WDYT?

SGTM

**Comment by Liam-Tait** [comment]
A larger change to consider. Should collections use generators? This would be breaking change.

Generators give lazy evaluation, memory efficiency, and sometimes better performance

Example:
```typescript
function* takeWhile<T>(
  iterable: Iterable<T>,
  predicate: (el: T) => boolean,
): Generator<T> {
  for (const element of iterable) {
    console.log(`takeWhile(): ${element}`);
    if (!predicate(element)) {
      break;
    }
    yield element;
  }
}

function* map<T, U>(
  iterable: Iterable<T>,
  transform: (el: T) => U,
): Generator<U> {
  for (const element of iterable) {
    console.log(`map(): ${element}`);
    yield transform(element);
  }
}

const arr = [1, 2, 3, 4, 5, 6, 7, 8, 9];
const result = takeWhile(map(arr, (n) => n * 100), n => n < 500)
console.log([...result])
```

**Comment by iuioiua** [comment]
Sorry for the delay. We're deciding how to best handle these changes that should probably be considered unstable.

**Comment by Liam-Tait** [comment]
No problem. Let me know if you need anything from me

**Comment by kt3k** [comment]
We decided to separate unstable feature from stable features more clearly (as described in #5920 ) to make it clear which part is stable and which part is not.

We are going to move this PR's implementation to `unstable_take_while.ts` (which will be available from JSR with the path `jsr:@std/collections/unstable-take-while` ) before merging.

**Review by iuioiua — APPROVED** [review]
Sorry for the delay. We've made a few tweaks, and now, LGTM! Thank you.

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
