### PR TITLE
test(bytes): fix typo in test description

### PR DESCRIPTION
**Pull request by Binsk-dev**
Fix typo in test description.

### CODE REVIEW

**Review by kt3k — APPROVED** [review]
LGTM. Thanks!

**Comment by kt3k** [comment]
a bit curious why this wasn't caught by our typo checker in CI

**Comment by Binsk-dev** [comment]
@kt3k I think it's because of the following line, clearing that setting caught the wrong typo.
https://github.com/denoland/std/blob/69858cfd7b917ac4cd67a9c0557a2c6d223e2d7f/.github/typos.toml#L14

**Comment by kt3k** [comment]
Ah, thanks for looking into it!

**Pull request merged**
