### PR TITLE
docs: use caption for doc example titles

### PR DESCRIPTION
**Pull request by nayeemrmn**
The titles as written before would mess up the formatting in VSCode. This puts them in `<caption>` tags as sort of suggested in https://jsdoc.app/tags-example (the way it's written there also doesn't work, though). It also needs an empty line after in the case the caption spans multiple lines.

### CODE REVIEW

**Comment by nayeemrmn** [comment]
We're probably gonna replace the caption formatting in the language server instead

**Comment by iuioiua** [comment]
Are you able to provide before/after shots? I can't seem to see where formatting in VSCode is getting messed up.

**Comment by kt3k** [comment]
I don't find problem with existing rendering either.

Also always requiring `<caption></caption>` doesn't feel like ideal DX.

**Comment by iuioiua** [comment]
To clarify Nayeem's previous comment, we'll likely not proceed with this change. But rather, file an issue with VSCode.

**Pull request closed without merging**
