### PR TITLE
BREAKING(fs): throw `Deno.errors.NotFound` instead of `WalkError` in `walk[Sync]()`

### PR DESCRIPTION
**Pull request by iuioiua**
### What's changed

[`walk()`](https://jsr.io/@std/fs/doc/walk/~/walk) and [`walkSync()`](https://jsr.io/@std/fs/doc/walk/~/walkSync) now naturally throw [`Deno.errors.NotFound`](https://docs.deno.com/api/deno/~/Deno.errors#namespace_deno_errors_notfound) instead of throwing `WalkError`. The `root` property has also been removed and the `message` property no longer includes the normalized path.

### Motivation

This change was made to allow these functions to delegate error throwing functionality to the Deno runtime, which provides sufficient context naturally. This also removes a dependency on `@std/path/normalize` and slightly reduces the API surface area of `@std/fs/walk`.

### Migration guide

To migrate, compare against `Deno.errors.NotFound` instead of `WalkError` when error-handling `walk()`.

```diff
- import { walk, WalkError } from "@std/fs/walk";
+ import { walk } from "@std/fs/walk";

const root = "../my-dir";

try {
  await Array.fromAsync(
    walk(root),
    async () => await Deno.remove(root, { recursive: true }),
  );
} catch (error) {
- if (error instanceof WalkError) {
+ if (error instanceof Deno.errors.NotFound) {
    // ...
  }
}
```

### Related

Towards #5476

### CODE REVIEW

**Comment by kt3k** [comment]
`WalkError.path` seems to have a usage https://github.com/denoland/std/issues/3023#issuecomment-1387458640

**Comment by iuioiua** [comment]
That suggestion was made as a passing remark rather than being triggered from a reported need from a user. After recent work on errors in the codebase, I'm becoming more convinced that throwing naturally is sufficient in almost all cases. If it's good enough for the runtime, I think it's good enough for the Standard Library.

**Comment by iuioiua** [comment]
Furthermore, `Deno.errors.NotFound` naturally provides clearer context for the error.

**Comment by kt3k** [comment]
> Furthermore, Deno.errors.NotFound naturally provides clearer context for the error.

`WalkError.prototype.root` gives the root path of `walk`. On the other hand, `Deno.error.NotFound` only shows the exact path, which was not found. The same information is not available with this change.

**Comment by kt3k** [comment]
@lowlighter and @lambdalisue are the users of WalkError in open source https://github.com/search?q=WalkError+std%2Ffs&type=code

What do you think about this change?

**Comment by kt3k** [comment]
Also I think @binyamin uses this in some projects https://github.com/denoland/std/issues/3023#issuecomment-1387458640

@binyamin Do you still use `WalkError` in your projects? What do you think about this change?

**Comment by lambdalisue** [comment]
If the change is clearly mentioned in the release notes, I'm fine with it. In fact, I prefer `Deno.errors.NotFound` over `WalkError` because users of `walk()` can wrap the error themselves if they need `root` information. I believe that certain responsibilities should lie with the users rather than the providers.

**Comment by marvinhagemeister** [comment]
+1 on going with `Deno.errors.NotFound`. It feels more consistent with the rest of Deno to me as other file system APIs throw that too.

**Comment by lowlighter** [comment]
I concur with what have been already said

**Review by kt3k — APPROVED** [review]
Thanks for the feedbacks/comments!

LGTM

**Pull request merged**
