### PR TITLE
feat(assert): add `options` parameter to `AssertionError` constructor

### PR DESCRIPTION
**Pull request by jsejcksn**
Ref:

- https://github.com/denoland/std/issues/5476#issuecomment-2254261250

### CODE REVIEW

**Review by iuioiua — CHANGES_REQUESTED** [review]
Are you able to add a test the ensures that the `cause` correctly propagates? Also, can you please add an example showing this behavior?

**Comment by jsejcksn** [comment]
@iuioiua

> Are you able to add a test the ensures that the `cause` correctly propagates?

I didn't see a test module for this class, but I'm happy to create one. I'll add an equality test for the error `message` property parameter as well.

> Also, can you please add an example showing this behavior?

I'm not sure what you have in mind. Do you essentially want me to copy the body of the test? If not, can you make a suggestion?

**Comment by jsejcksn** [comment]
@iuioiua I added tests using actual control flow. As a contrived but simpler alternative, it could look like this:

```ts
Deno.test("AssertionError", () => {
  const originalError = new Error("foo");
  const assertionError = new AssertionError("bar", { cause: originalError });
  assertStrictEquals(assertionError.message, "bar");
  assertStrictEquals(assertionError.cause, originalError);
});

```

…but that doesn't represent intended usage in exception-handling control flow. With that juxtaposition available, what are your current thoughts about the following?

1. the structure/style of the tests
2. the content of the example documentation

**Comment by jsejcksn** [comment]
Aside: I'm seeing ci failures in the lint steps ([example](https://github.com/denoland/std/actions/runs/10131143544/job/28013460563?pr=5561)). They are for the rule [`no-unreachable`](https://lint.deno.land/rules/no-unreachable), and I think they shouldn't be happening (the tests prove that the lint diagnostic is wrong). Perhaps a new issue should be raised in that repository…

**Review by iuioiua — APPROVED** [review]
I've cleaned up the example and test (they don't have to be too thorough, as this error is used to a large extend throughout testing in the codebase). Now, LGTM! Thanks!

**Comment by jsejcksn** [comment]
> they don't have to be too thorough

@iuioiua Ok, sounds good. I did make one more change: using strict equality comparison for the `error.cause` because I think it's important to illustrate that they aren't just the same shapes, but actually the same value.

Do you have any thoughts about https://github.com/denoland/std/pull/5561#issuecomment-2254477232?

**Comment by iuioiua** [comment]
> 29bb954

Yes please.

**Comment by jsejcksn** [comment]
> > [29bb954](https://github.com/denoland/std/commit/29bb95420bbb54a29c10723e2bae02b9de1cb4fd)
> 
> Yes please.

Ref:

- https://github.com/denoland/deno_lint/issues/1303

**Pull request merged**
