### PR TITLE
chore: release 2024.09.04

### PR DESCRIPTION
**Pull request by denobot**
The following updates are detected:

| module   | from    | to      | type  |
|----------|---------|---------|-------|
|archive|0.225.1|0.225.2|patch|
|assert|1.0.3|1.0.4|patch|
|async|1.0.4|1.0.5|patch|
|cache|0.1.1|0.1.2|patch|
|cli|1.0.4|1.0.5|patch|
|csv|1.0.2|1.0.3|patch|
|datetime|0.225.1|0.225.2|patch|
|dotenv|0.225.1|0.225.2|patch|
|encoding|1.0.3|1.0.4|patch|
|expect|1.0.1|1.0.2|patch|
|fmt|1.0.1|1.0.2|patch|
|front-matter|1.0.3|1.0.4|patch|
|fs|1.0.2|1.0.3|patch|
|http|1.0.4|1.0.5|patch|
|internal|1.0.2|1.0.3|patch|
|io|0.224.6|0.224.7|patch|
|log|0.224.6|0.224.7|patch|
|msgpack|1.0.1|1.0.2|patch|
|net|1.0.1|1.0.2|patch|
|path|1.0.3|1.0.4|patch|
|semver|1.0.2|1.0.3|patch|
|streams|1.0.3|1.0.4|patch|
|tar|0.0.0|0.1.0|minor|
|testing|1.0.1|1.0.2|patch|
|text|1.0.4|1.0.5|patch|
|url|0.225.0|0.225.1|patch|
|uuid|1.0.2|1.0.3|patch|
|webgpu|0.224.6|0.224.7|patch|
|yaml|1.0.4|1.0.5|patch|

Please ensure:
- [x] Versions in deno.json files are updated correctly
- [x] Releases.md is updated correctly

The following commits are ignored:

- [chore: prepare for `@std/tar` package (#5906)](/denoland/std/commit/5aa54eff2b817cc2bb41c40274b8240a307f6782)
- [chore: specify import map path in version_bump workflow (#5826)](/denoland/std/commit/0ebec104507acf6c1a26d89a0d730aecfd40f4c4)

---

To make edits to this PR:

```sh
git fetch upstream release-2024-09-04-10-32-06 && git checkout -b release-2024-09-04-10-32-06 upstream/release-2024-09-04-10-32-06
```

### CODE REVIEW

**Review by kt3k — APPROVED** [review]

**Comment by martin-braun** [comment]
We are close to a full stabilization of `std` to v1. Are there any requirements left to stabilize `dotenv`?

**Comment by kt3k** [comment]
`dotenv` remains unstable because it largely overlaps with `deno run --env` option behavior. We currently have no idea how to make progress about it. We probably need more feedbacks from the community about both `std/dotenv` and `deno run --env`.

**Comment by martin-braun** [comment]
@kt3k Thanks, I just learned about `--env`. For me it seems to make `dotenv` obsolete since the inclusion of `--allow-env` is mandatory in any case. Is there an ongoing discussion about this issue?

**Comment by iuioiua** [comment]
`@std/dotenv` can be used when the programmer wants the environment variables to be read during program execution. `--env` can only read the `.env` file at startup.

**Pull request merged**
