### PR TITLE
chore: remove obsolete log

### PR DESCRIPTION
**Pull request by timreichen**
**Changes**
This PR removes success logs at the end of the check.

**Reasoning**
Other tools only log if they fail.

### CODE REVIEW

**Comment by iuioiua** [comment]
Does this deliberately target #5612?

**Review by iuioiua — COMMENTED** [review]
I'm impartial to this change. I'll defer to Yoshiya's review.

**Comment by kt3k** [comment]
I'm not in favor. These logs are useful.

**Comment by timreichen** [comment]
@kt3k should all tools log a success message if zhey do not fail?

**Comment by kt3k** [comment]
I don't think we need strict consistency with tools. We should rather spend time on polishing user-facing APIs (in my opinion)

**Pull request closed without merging**
